#!/bin/bash
# Make sure student user exists
if ! grep student /etc/passwd; then
    useradd student
    echo -e 'student\nstudent\n' | passwd student
fi

if [ ! -d "/var/home/student" ]; then
    mkhomedir_helper student
fi
