#!/bin/bash
# Make sure student user exists
if ! grep student /etc/passwd; then
    useradd student
    echo -e 'student\nstudent\n' | passwd student

    # Also fix grub since this might be the first boot
    grub2-switch-to-blscfg

    # Hide grub bootloader
    sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
    echo 'GRUB_TIMEOUT_STYLE=hidden' | tee -a /etc/default/grub 1>/dev/null
    echo 'GRUB_HIDDEN_TIMEOUT=1' | tee -a /etc/default/grub 1>/dev/null

    # Regenerate grub
    if [ -d /sys/firmware/efi ]; then
      sudo grub2-mkconfig -o /etc/grub2-efi.cfg
    else
      sudo grub2-mkconfig -o /etc/grub2.cfg
    fi
fi

if [ ! -d "/var/home/student" ]; then
    mkhomedir_helper student
fi

# Set default power profile to powersave
cat << PPD > /etc/tuned/ppd.conf
[main]
# The default PPD profile
default=power-saver

[profiles]
# PPD = TuneD
power-saver=powersave
balanced=balanced
performance=throughput-performance
PPD
